---
title: "TO 414 Project 1"
author: "Chandramouli Krishnan, Rahul Rokkam, Kristian Olsen, Nick Davis, Lena Ivens, Sean Conway"
date: "10/11/2020"
output: 
  html_document: 
    toc: yes
    toc_float: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Clean Data
```{r echo = FALSE}
prospectData = read.csv("ProjectA_Listings2013.csv")
#head(prospectData)

#summary(prospectData)
#potential factors: loan status, scorexRange, income range, employment status, borrower state, 

# potential numeric: 
#potential boolean: incomeverification

prospectData$loan_status = as.factor(prospectData$loan_status)
prospectData$scorex = as.factor(prospectData$scorex)
prospectData$income_range = as.factor(prospectData$income_range)
prospectData$employment_status_description = as.factor(prospectData$employment_status_description)
prospectData$borrower_state = as.factor(prospectData$borrower_state)
prospectData$income_verifiable = as.logical(prospectData$income_verifiable)
#prospectData$prosper_rating = as.factor(prospectData$prosper_rating)

prospectData$Defaulted = as.factor(ifelse(prospectData$loan_status_description == "DEFAULTED", 1, ifelse(prospectData$loan_status_description == "CHARGEOFF", 1, 0)))

table(prospectData$Defaulted)


#unique(prospectData$prosper_rating)

summary(prospectData)
```
To clean the Data, we changed the following variables to factors and logicals:

* loan_status
* scorex
* income_range
* employment_status_description
* borrower_state
* income_verifiable





## Linear Regression
```{r echo = FALSE}
prospectDataNoNA = na.omit(prospectData)

# should we be including "loan_status" and "loan_status_description in this"?????
#linreg = lm(borrower_rate ~ number_of_days + principal_balance + loan_status + amount_funded + listing_term + listing_monthly_payment + scorex + prosper_score + listing_category_id + income_range + stated_monthly_income + income_verifiable + dti_wprosper_loan + employment_status_description + months_employed + monthly_debt + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + open_credit_lines + bankcard_utilization + total_open_revolving_accounts + installment_balance + real_estate_balance + revolving_balance + real_estate_payment + revolving_available_percent + total_inquiries + satisfactory_accounts + was_delinquent_derog + delinquencies_over30_days + delinquencies_over60_days,data = prospectDataNoNA)


linregWithInteractions = lm(borrower_rate ~ number_of_days + principal_balance + loan_status + amount_funded + listing_term + listing_monthly_payment + scorex + prosper_score + listing_category_id + income_range + stated_monthly_income + income_verifiable + dti_wprosper_loan + employment_status_description + months_employed + monthly_debt + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + open_credit_lines + bankcard_utilization + total_open_revolving_accounts + installment_balance + real_estate_balance + revolving_balance + real_estate_payment + revolving_available_percent + total_inquiries + satisfactory_accounts + was_delinquent_derog + delinquencies_over30_days + delinquencies_over60_days + prosper_rating*prosper_score + income_range*stated_monthly_income + current_delinquencies*delinquencies_last7_years + public_records_last10_years*public_records_last12_months + credit_lines_last7_years*inquiries_last6_months,data = prospectDataNoNA)


#summary(linreg)

#stepModel <- step(linreg, direction = "backward")
stepModel2 <- step(linregWithInteractions, direction = "backward")

#summary(stepModel)
summary(stepModel2)
```

```{}
To create our Linear Regression, we first used all variables that we deemed pertinent to the regression - 
excluding the dependent variable (borrower_rate), irrelevant variables (loan_origination_date, occupation, 
borrower_state, borrower_city, lender_indicator, first_recorded_credit_line), variables that repeated themselves as both factors and integers (prosper_rating, income_range_description), and those that appeared as NA on our 
regression (total_trade_items, now_delinquent_derog, delinquencies_over_90_days)

We then used the function step() to...(whatever step does)...

loan_status_description???


```



## Logistic Regression
```{r echo = TRUE}


#Test and train set b/c this montly income stuff doesn't make sense
set.seed(1234)
testrows = sample(1:nrow(prospectDataNoNA),100)

trainingData = prospectDataNoNA[-testrows,]
testData = prospectDataNoNA[testrows,]
summary(testData$Defaulted)

#logreg = glm(Defaulted ~ number_of_days + principal_balance + amount_funded + listing_term + listing_monthly_payment + prosper_score + income_range + stated_monthly_income + months_employed + monthly_debt + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + open_credit_lines + bankcard_utilization + total_open_revolving_accounts + installment_balance + real_estate_balance + revolving_balance + real_estate_payment + revolving_available_percent + total_inquiries + satisfactory_accounts + was_delinquent_derog + delinquencies_over30_days + delinquencies_over60_days + scorex + income_range + employment_status_description + income_verifiable, data = prospectDataNoNA, family = "binomial")


#logreg1 = glm(Defaulted ~ number_of_days + principal_balance + amount_funded + listing_term + listing_monthly_payment + prosper_score + income_range + stated_monthly_income + months_employed + monthly_debt + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + open_credit_lines, data = prospectDataNoNA, family = "binomial")

logreg2 = glm(Defaulted ~ number_of_days + principal_balance + amount_funded + listing_term + listing_monthly_payment + prosper_score + income_range + stated_monthly_income + months_employed + monthly_debt + current_delinquencies + delinquencies_last7_years, data = prospectDataNoNA, family = "binomial")

logreg3 =  glm(Defaulted ~ stated_monthly_income , data = trainingData, family = "binomial")

#logRegWithInteraction <- glm(Defaulted ~ number_of_days + principal_balance + amount_funded + listing_term + listing_monthly_payment + prosper_score + income_range + stated_monthly_income + months_employed + monthly_debt + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + open_credit_lines + bankcard_utilization + total_open_revolving_accounts + installment_balance + real_estate_balance + revolving_balance + real_estate_payment + revolving_available_percent + total_inquiries + satisfactory_accounts + was_delinquent_derog + delinquencies_over30_days + delinquencies_over60_days + scorex + income_range + employment_status_description + income_verifiable + prosper_rating*prosper_score + income_range*stated_monthly_income + current_delinquencies*delinquencies_last7_years + public_records_last10_years*public_records_last12_months + credit_lines_last7_years*inquiries_last6_months, data = prospectDataNoNA, family = "binomial")

#summary(prospectData)

#summary(logReg)

stepLogreg <- step(logreg2, direction = "backward")


#summary(stepLogreg)


#finalModel = glm(formula = Defaulted ~ number_of_days + principal_balance + amount_funded + listing_term + listing_monthly_payment + prosper_score + stated_monthly_income + delinquencies_last7_years + public_records_last12_months + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + bankcard_utilization + revolving_balance + total_inquiries + was_delinquent_derog + delinquencies_over30_days + scorex + employment_status_description + income_verifiable, family = "binomial", data = prospectDataNoNA)

finalModel = stepLogreg

summary(finalModel)

predictedTest = predict(finalModel,newdata = testData,type = "response")
summary(predictedTest)
predictedTest = as.factor(ifelse(predictedTest > .5, 1,0))

table(predictedTest,testData$Defaulted)
```


```{r echo=TRUE}

logisticVar =  finalModel$coefficients
#logisticVar
linearVar = stepModel$coefficients
#linearVar

differentVars = setdiff(names(linearVar),names(logisticVar))
differentVars



```